### ISSUE TITLE
Double definition not detected

### ISSUE THREAD

**Issue by jfdm2** [conjure-cp/conjure#460] opened 2019-10-24 14:18 UTC
If you have
```
given n : int(..0)
given n : int(1..3,9..)
find a : int(-50..50)
such that a = n+n
```
with *.param
```
letting n be -5
letting n be 1
```
the first ``given n`` is ignored. Maybe we want it because of param refinement in several steps, but should be documented and it would be useful to output a warning, just in case it wasn't redefined on purpose.

If you have
```
letting n be -5
letting n be 1
find a : int(-50..50)
such that a = n+n
```
it ignores first ``letting n`` and so gives ``a=2`` as answer. A warning or error message should be outputed.

**Comment by ozgurakgun** [comment] 2019-10-24 14:19
Thanks. Just to note, this is a duplicate of #457.

**Comment by jfdm2** [comment] 2019-10-24 14:22
Oh right, I should have checked the other issues first :$
Well, it shows it also happens for given and letting :p

**Closed as completed** 2023-02-20 12:36 UTC
