### ISSUE TITLE
Cannot compile conjure on Apple Silicon

### ISSUE THREAD

**Issue by SaadAttieh** [conjure-cp/conjure#532] opened 2022-09-09 18:23 UTC
```
Saads-MacBook-Air:conjure saadattieh$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
giSaads-MacBook-Air:conjure saadattieh$ git pull
Already up to date.
Saads-MacBook-Air:conjure saadattieh$ make
Using GHC version 8.6 (major version)
Set the environment variable GHC_VERSION to change this location.
For example: "GHC_VERSION=8.4 make install"
Supported versions: 8.4, 8.6

Installing executables to /Users/saadattieh/.local/bin
Add this directory to your PATH.
Set the environment variable BIN_DIR to change this location
For example: "BIN_DIR=your/preferred/path make install"

Using Stack file: etc/hs-deps/stack-8.6.yaml
lrwxr-xr-x  1 saadattieh  admin  39  3 Aug 18:12 /opt/homebrew/bin/stack -> ../Cellar/haskell-stack/2.7.5/bin/stack
Version 2.7.5 aarch64
Compiled with:
- Cabal-3.2.1.0
- Cabal-syntax-3.6.0.0
- Glob-0.10.2
- OneTuple-0.3.1
- aeson-1.5.6.0
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.11.1
- ansi-wl-pprint-0.6.9
- appar-0.1.8
- array-0.5.4.0
- asn1-encoding-0.9.6
- asn1-parse-0.9.5
- asn1-types-0.3.4
- assoc-1.0.2
- async-2.2.4
- attoparsec-0.14.4
- attoparsec-0.14.4
- attoparsec-iso8601-1.0.2.1
- auto-update-0.1.6
- base-4.14.3.0
- base-compat-0.12.1
- base-compat-batteries-0.12.1
- base-orphans-0.8.6
- base16-bytestring-1.0.2.0
- base64-bytestring-1.2.1.0
- basement-0.0.14
- bifunctors-5.5.11
- binary-0.8.8.0
- blaze-builder-0.4.2.2
- blaze-html-0.9.1.2
- blaze-markup-0.8.2.8
- byteorder-1.0.4
- bytestring-0.10.12.0
- casa-client-0.0.1
- casa-types-0.0.2
- case-insensitive-1.2.1.0
- cereal-0.5.8.2
- clock-0.8.3
- colour-2.3.6
- comonad-5.0.8
- conduit-1.3.4.2
- conduit-combinators-1.3.0
- conduit-extra-1.3.5
- connection-0.3.1
- containers-0.6.5.1
- cookie-0.4.5
- cryptohash-sha256-0.11.102.1
- cryptonite-0.29
- cryptonite-conduit-0.2.2
- data-default-class-0.1.2.0
- data-fix-0.3.2
- deepseq-1.4.4.0
- digest-0.0.1.3
- directory-1.3.6.0
- distributive-0.6.2.1
- dlist-1.0
- easy-file-0.2.2
- echo-0.1.4
- ed25519-0.0.5.0
- exceptions-0.10.4
- extra-1.7.10
- fast-logger-3.1.1
- file-embed-0.0.15.0
- filelock-0.1.1.5
- filepath-1.4.2.1
- fsnotify-0.3.0.1
- generic-deriving-1.14.1
- ghc-boot-th-8.10.7
- ghc-prim-0.6.1
- githash-0.1.6.2
- hackage-security-0.6.2.1
- hashable-1.3.5.0
- hfsevents-0.1.6
- hi-file-parser-0.1.2.0
- hourglass-0.2.12
- hpack-0.34.6
- hpc-0.6.1.0
- http-api-data-0.4.3
- http-client-0.7.11
- http-client-tls-0.3.6.1
- http-conduit-2.3.8
- http-download-0.2.0.0
- http-types-0.12.3
- indexed-traversable-0.1.2
- infer-license-0.2.0
- integer-gmp-1.0.3.0
- integer-logarithms-1.0.3.1
- iproute-1.7.12
- libyaml-0.1.2
- lift-type-0.1.0.1
- lifted-base-0.2.3.12
- lukko-0.1.1.3
- megaparsec-9.2.0
- memory-0.17.0
- microlens-0.4.12.0
- microlens-mtl-0.2.0.1
- microlens-th-0.4.3.10
- mime-types-0.1.0.9
- mintty-0.1.3
- monad-control-1.0.3.1
- monad-logger-0.3.36
- monad-loops-0.4.3
- mono-traversable-1.0.15.3
- mtl-2.2.2
- mtl-compat-0.2.2
- mustache-2.3.2
- neat-interpolation-0.5.1.3
- network-3.1.2.7
- network-uri-2.6.4.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- open-browser-0.2.1.0
- optparse-applicative-0.17.0.0
- optparse-simple-0.1.1.4
- pantry-0.5.4
- parsec-3.1.14.0
- parser-combinators-1.3.0
- path-0.9.2
- path-io-1.7.0
- path-pieces-0.2.1
- pem-0.2.4
- persistent-2.13.3.0
- persistent-sqlite-2.13.1.0
- persistent-template-2.12.0.0
- pretty-1.1.3.6
- primitive-0.7.3.0
- process-1.6.13.2
- project-template-0.2.1.0
- random-1.2.1
- resource-pool-0.2.3.2
- resourcet-1.2.4.3
- retry-0.9.2.0
- rio-0.1.21.0
- rio-orphans-0.1.2.0
- rio-prettyprint-0.1.1.0
- rts-1.0.1
- safe-0.3.19
- safe-exceptions-0.1.7.2
- scientific-0.3.7.0
- semigroups-0.20
- silently-1.2.5.2
- socks-0.6.1
- split-0.2.3.4
- splitmix-0.1.0.4
- stm-2.5.0.1
- stm-chans-3.0.0.6
- streaming-commons-0.2.2.4
- strict-0.4.0.1
- syb-0.7.2.1
- tagged-0.8.6.1
- tar-0.5.1.1
- tar-conduit-0.3.2
- template-haskell-2.16.0.0
- temporary-1.3
- text-1.2.4.1
- text-metrics-0.3.2
- th-abstraction-0.4.3.0
- th-compat-0.1.3
- th-expand-syns-0.4.9.0
- th-lift-0.8.2
- th-lift-instances-0.1.19
- th-reify-many-0.1.10
- these-1.1.1.1
- time-1.9.3
- time-compat-1.9.6.1
- tls-1.5.7
- transformers-0.5.6.2
- transformers-base-0.4.6
- transformers-compat-0.7.1
- typed-process-0.2.8.0
- unicode-data-0.3.0
- unicode-transforms-0.4.0
- unix-2.7.2.2
- unix-compat-0.5.4
- unix-time-0.4.7
- unliftio-0.2.21.0
- unliftio-core-0.2.0.1
- unordered-containers-0.2.16.0
- uuid-types-1.0.5
- vault-0.3.1.5
- vector-0.12.3.1
- vector-algorithms-0.8.0.4
- x509-1.7.6
- x509-store-1.6.9
- x509-system-1.6.7
- x509-validation-1.6.12
- yaml-0.11.8.0
- zip-archive-0.4.2.1
- zlib-0.6.2.3

Warning: this is an unsupported build that may use different versions of
dependencies and GHC than the officially released binaries, and therefore may
not behave identically.  If you encounter problems, please try the latest
official build by running 'stack upgrade --force-download'.

No setup information found for ghc-8.6.5 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'macosx-aarch64'.
Supported versions: ghc-8.10.5, ghc-8.10.6, ghc-8.10.7, ghc-9.0.2, ghc-9.2.1, ghc-9.2.2, ghc-9.2.3, ghc-9.2.4, ghc-9.4.1, ghc-9.4.2
make: *** [install] Error 1
Saads-MacBook-Air:conjure saadattieh$ 
```

**Comment by ozgurakgun** [comment] 2022-09-09 19:13
Oh that's surprising as I develop it on an M1 machine :)

Did you migrate from an Intel machine using time machine by any chance?

**Comment by ott2** [comment] 2022-09-16 17:16
Another data point: on my M1 MBP migrated from Intel, the Conjure makefile ends up running `stack --local-bin-path $HOME/.local/bin setup` and this (Intel-built) stack 8.6 then tries to download and install an Intel GHC 8.6.5.

**Comment by ozgurakgun** [comment] 2022-09-21 14:38
Trying to reproduce this.

```
$ rm -rf ~/.stack ~/.ghc # remove everything including stack and any previously installed compilers
$ mkdir ~/tmp ; cd ~/tmp # fresh new directory
$ git clone git@github.com:conjure-cp/conjure.git
$ cd conjure
$ make
```

Took a long time (18 minutes), downloaded GHC-8.6.5 and the entire Haskell ecosystem, but ran without any errors.

Just make sure ~/.local/bin is in PATH or set BIN_DIR to something that is in your path.

So, I cannot reproduce this at the moment.

**Comment by ozgurakgun** [comment] 2022-11-03 09:30
Closing since I cannot reproduce.

**Closed by ozgurakgun** 2022-11-03 09:30 UTC
